# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='userid',
        ),
    ]
