# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_remove_upload_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload',
            new_name='upload1',
        ),
    ]
